547
keeleinstituut/tv-web pull request #159
Opened 2023-11-15 09:12 UTC by IngaSokman

2023-11-15 18:10 UTC, KaarelKa commented
Merged a bunch of things, so we have some merge conflicts here

2023-11-16 12:25 UTC, VaabelMaret approved these changes

2023-11-16 12:26 UTC, rebekkabb approved these changes
tested, lgtm!

2023-11-16 14:50 UTC, KaarelKa requested changes

2023-11-16 14:52 UTC, KaarelKa approved these changes

2023-11-16 14:52 UTC, merged