311 empty tm
keeleinstituut/tv-web pull request #209
Opened 2023-12-11 12:58 UTC by VaabelMaret

NOTE: BE task is on CR. Can't test right now.
https://github.com/keeleinstituut/tv-translation-order/pull/106/files

2023-12-13 12:23 UTC, KaarelKa requested changes

2023-12-13 12:23 UTC, KaarelKa commented on src/components/organisms/TranslationMemoriesSection/TranslationMemoriesSection.tsx
>          disabled={disabled}
**[blocker]**

Would be good to show a loader as well

2023-12-13 12:23 UTC, KaarelKa commented on src/hooks/requests/useTranslationMemories.ts
> +    onSuccess: ({ data }) => {
**[blocker]**

Can't merge right now, "undefined" will be added to the list of translationMemories, which will crash the app in TranslationMemorySection. This is waiting for BE to add the missing data to the response ?

2023-12-14 14:21 UTC, VaabelMaret commented
ready to review, BE task is merged

2023-12-15 06:51 UTC, merged